services:
  invoice-process-application:
    container_name: invoice-process-application
    image:  goafabric/invoice-process${_Values_image_native}:${_Values_image_tag}
    restart: 'no'
    command: "-Xmx32m"

    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      disable: true #disabled for native images because of no curl
      interval: 5s
      timeout: 10s
      retries: 5

    volumes:
      - tmp_invoice:/tmp
      - applogs_invoice:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      server.port: "8080"
      server.tomcat.threads.max: "20"
      server.forward-headers-strategy: FRAMEWORK

      process.autostart: false

      #security
      security.authentication.enabled: "false"

      #monitoring
      management.endpoint.health.show-details: always
      management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

      #zipkin/jaeger
      spring.application.name: "invoice-process"
      management.tracing.sampling.probability: "1.0"
      logging.level.io.opentelemetry: "OFF"
      management.otlp.tracing.endpoint: "http://host.docker.internal:4318/v1/traces"

      #adapter
      adapter.coreservice.url: "http://application:50800"
      adapter.catalogservice.url: "http://catalog-service-application:8080"

      #log levels
      logging.level.root: "WARN"
      logging.level.org.goafabric: "INFO"
      logging.level.org.springframework: "INFO"