#application
server:
  port: 50500
  tomcat.threads.max: 20
  forward-headers-strategy: FRAMEWORK

#monitoring
management:
    endpoint:
      health:
        show-details: never
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

#tracing
spring.application.name: invoice-process
management.tracing.sampling.probability: "1.0"
logging.level.io.opentelemetry.exporter: "OFF"
management.otlp.tracing.endpoint: "http://localhost:4318/v1/traces"

#security
security.authentication.enabled: true
spring.security.user.name: "admin"
spring.security.user.password: "admin"

#logging
logging.pattern.level: "%5p tenantId=%X{tenantId:-}" #"%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#vthreads
spring.threads.virtual.enabled: "true"

#adapter
adapter:
  timeout: 10000
  organizationservice:
    url: http://localhost:50800
